apiVersion: v1
kind: Pod
metadata:
  name: fsx-app
spec:
  containers:
  - name: trainer
    image: tensorflow/tensorflow:2.12.0
    command: [ "sh", "-c", "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: fsx-storage
      mountPath: /mnt/fsx
  volumes:
  - name: fsx-storage
    persistentVolumeClaim:
      claimName: fsx-pvc
