apiVersion: v1
kind: configMap
metadata:
  name: prometehus-config
  lables:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'prometheus'
        static_config:
          - targets: ['localhost:9090']

      - job_name: 'demo-app'
        static_config:
          - targets: ['demo-app:5000']
