apiVersion: v1
kind: Pod
metadata:
  name: pod-toleration
spec:
  tolerations:
  - key: "key"
    operator:  "Equal"
    value: "value"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx
    