apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-rollout-bluegreen
  namespace: demo
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: demo-app-active
      previewService: demo-app-preview
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: nginx:1.19
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-active
  namespace: demo
spec:
  selector:
    app: demo-app
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-preview
  namespace: demo
spec:
  selector:
    app: demo-app
  ports:
    - port: 80
      targetPort: 80
