apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-rollout-canary
  namespace: demo
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration : 30s}
        - setWeight: 50
        - pause: {duration: 60s}
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: nginx:1.22
        ports:
        - containerPort: 8080