apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-search
  template:
    metadata:
      labels:
        app: elastic-search
    spec:
      containers:
      - name: elastic-search
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"   # 👈 limit JVM heap to 512MB
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: elastic-search
spec:
  selector:
    app: elastic-search
  ports:
  - port: 9200
    targetPort: 9200